-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "restePasswordExpiresAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "passUpdateAt" SET DATA TYPE TIMESTAMPTZ(3);
